name: Build workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        ocaml-compiler:
          - 3.11.2

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          submodules: recursive

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install Ubuntu packages
        run: sudo apt install -y gcc opam autoconf automake make gperf python3 indent emacs flex bison

      - name: Build Locksmith
        run: ./scripts/build.sh

      - name: Test
        run: ./scripts/test.sh
        
